# -*- coding: utf-8 -*-
"""AI Image Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-LlCbEX0WUQIzdNnYZgxWXvg5w2Dhm5
"""

!pip install fastapi uvicorn pyngrok nest_asyncio diffusers transformers accelerate torch --quiet

from pyngrok import ngrok

ngrok.set_auth_token("xxxxxxxxxxxxxxxxxxxx-Your-ngrok-token-here")

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from diffusers import AutoPipelineForText2Image
import torch
import uuid
import os

app = FastAPI()

# Enable CORS so frontend can call the API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

print("Loading AI model...")

pipe = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/sd-turbo",
    torch_dtype=torch.float16
).to("cuda")

print("Model loaded successfully")

IMAGE_DIR = "generated"
os.makedirs(IMAGE_DIR, exist_ok=True)

@app.get("/")
def home():
    return {"message": "AI Image Generator Running"}

@app.get("/generate")
def generate(prompt: str):

    image = pipe(
        prompt,
        num_inference_steps=2,
        guidance_scale=0.0
    ).images[0]

    filename = str(uuid.uuid4()) + ".png"
    path = os.path.join(IMAGE_DIR, filename)

    image.save(path)

    return {"image_url": f"/download/{filename}"}

@app.get("/download/{filename}")
def download_image(filename: str):

    path = os.path.join(IMAGE_DIR, filename)

    return FileResponse(path, media_type="image/png", filename=filename)

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

threading.Thread(target=run).start()

from pyngrok import ngrok
ngrok.kill()

public_url = ngrok.connect(8000)
print(public_url)

