# -*- coding: utf-8 -*-
"""Text to Image Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwCuANqpiIk283TAF1421PcGG0ZmHJWh
"""

!nvidia-smi

!pip install diffusers transformers accelerate

from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import torch

!pip show torch

model_id1 = "dreamlike-art/dreamlike-diffusion-1.0"
model_id2 = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = StableDiffusionPipeline.from_pretrained(model_id1, torch_dtype=torch.float16, use_safetensors=True)
pipe = pipe.to("cuda")

prompt = """dreamlikeart, a grungy woman with rainbow hair, travelling between dimensions, dynamic pose, happy, sofr extreme broken, dainty figure, long hair straight down, torn kawali shirt and baggy jeans"""

image = pipe(prompt).images[0]

print("[PROMPT]: ",prompt)
plt.imshow(image);
plt.axis('off');

prompt2 = """A girl is sitting on a chair & She is accompanied by her tiger. Make sure to keep it cinematic and color to be golden iris"""

image = pipe(prompt2).images[0]

print('[PROMPT]: ', prompt2)
plt.imshow(image)
plt.axis('off')

"""Working With Stable Diffusion Parameters
- Negative Prompting
- num_interference_steps
- height
- weight
- num_images_per_prompt
"""

def generate_image(pipe, prompt, params):
  img = pipe(prompt, **params).images

  num_images = len(img)
  if num_images > 1:
    fig, ax = plt.subplots(nrows=1, ncols=num_images)
    for i in range(num_images):
      ax[i].imshow(img[i]);
      ax[i].axis('off');

  else:
    fig = plt.figure()
    plt.imshow(img[0]);
    plt.axis('off');
  plt.tight_layout()

prompt = """dreamlike , beautiful girl playing the festival of colors, draped in traditional Indian attire, throwing colors on each neighbours"""

params = {}

generate_image(pipe, prompt, params)

#Num inference steps

params = {'num_inference_steps': 100}

generate_image(pipe, prompt, params)

#Height-Width
params = {'num_inference_steps': 100, 'width': 512, 'height': int(1.5*640)}

generate_image(pipe, prompt, params)

#num_images_per_prompt
params = {'num_inference_steps': 100, 'num_images_per_prompt': 2}

generate_image(pipe, prompt, params)

#Negative prompt

image = {'num_inference_steps': 100, 'num_images_per_prompt': 2, 'negative_prompt': 'ugly, distorted, low quality'}

generate_image(pipe, prompt, params)

