# -*- coding: utf-8 -*-
"""Text to Audio Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15E9OQ0cK6M1BXDNHdbi7FgUmQRBj4ztv
"""

!pip install transformers

from transformers import pipeline

text = 'Python is high-level, general-purpose programming language.'

pipe = pipeline('text-to-speech', model='suno/bark-small', device='cuda')

output = pipe(text)

output

from IPython.display import Audio
Audio(output['audio'], rate=output['sampling_rate'])

